services:
  brainstormer-agent:
    build: ./brainstormer-agent
    env_file:
      - .env
  critic-agent:
    build: ./critic-agent
    env_file:
      - .env
  roadmap-agent:
    build: ./roadmap-agent
    env_file:
      - .env
  task-agent:
    build: ./task-agent
    env_file:
      - .env
  nginx-gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf