version: '3.8'

services:
  brainstormer-agent:
    build: ./brainstormer-agent
    env_file:
      - .env # <--- ADD THIS

  critic-agent:
    build: ./critic-agent
    env_file:
      - .env # <--- AND ADD THIS

  roadmap-agent:
      build: ./roadmap-agent
      env_file:
        - .env

  nginx-gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf